#!/usr/bin/python
# -*- coding: UTF-8 -*-
# 基本语法

"""
这是多行注释
这是多行注释
这是多行注释
"""

print "你好，世界"
a = """aaaaa
bbbbb
ccccc"""
print a

counter = 100  # 赋值整型变量
miles = 1000.0  # 浮点型
name = "John"  # 字符串

print counter
print miles
print name

num1 = 0.01
num2 = 0.02
num3 = 0.03

num4 = num1 + \
       num2 + \
       num3
print num4

import sys; x = 'runoob'; sys.stdout.write(x + '\n\n')

raw_input("\n\nPress the enter key to exit.")
